name: Publish Docker image
on:
  schedule:
    - cron: "20 4 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/auto-build-on-change.yml

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Check for base image updates
        id: check
        uses: lucacome/docker-image-update-checker@v2
        with:
          base-image: caddy:latest
          image: lewimbes/caddy-cloudflare:latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
        if: github.event_name != 'schedule' || steps.check.outputs.needs-updating == 'true'

      - name: Fetch Caddy version
        id: caddy
        shell: bash
        run: |
          set -euo pipefail
          url='https://raw.githubusercontent.com/docker-library/official-images/master/library/caddy'
          ver=$(curl -fsSL "$url" | grep -m1 '^Tags:' | \
              sed -E 's/Tags:[[:space:]]*([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          echo "full=$ver"                 >> "$GITHUB_OUTPUT"
          echo "major_minor=${ver%.*}"     >> "$GITHUB_OUTPUT"
          echo "major=${ver%%.*}"          >> "$GITHUB_OUTPUT"
          echo "Resolved Caddy version → $ver"
        if: github.event_name != 'schedule' || steps.check.outputs.needs-updating == 'true'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.event_name != 'schedule' || steps.check.outputs.needs-updating == 'true'

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'schedule' || steps.check.outputs.needs-updating == 'true'

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            lewimbes/caddy-cloudflare
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ steps.caddy.outputs.full }}
            type=raw,value=${{ steps.caddy.outputs.major_minor }}
            type=raw,value=${{ steps.caddy.outputs.major }}
            type=raw,value=latest
        if: github.event_name != 'schedule' || steps.check.outputs.needs-updating == 'true'

      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        if: github.event_name != 'schedule' || steps.check.outputs.needs-updating == 'true'

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
        if: github.event_name != 'schedule' || steps.check.outputs.needs-updating == 'true'
